apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 1.28.2
    chart: nginx-ingress
    helm:
      parameters:
        - name: controller.service.type
          value: ClusterIP
  project: default
  syncPolicy:
    automated: {}